#!/bin/bash

#kill process with previous brandon-bot
./stop
echo "
...
"
sleep 1

#pull latest from git
echo "pulling latest from git:"
git pull
echo "
...
"
sleep 1

#start updated brandon-bot
echo "awaken, brandon-bot"
./run

