#!/bin/bash

# Move brandon.log if it exists
date=$(date +"%Y%m%d%H%M")
if [ -f logs/brandon.log ]; then
    mv logs/brandon.log logs/old/brandon${date}.log
fi

touch logs/brandon.log

# Run brandon-bot in background.
# Redirect error output to /logs/wb_error.log
nohup python3 -u brandon.py >> logs/brandon.log 2>&1&
sleep 1
echo '
'

#make sure he's alive
echo "Alive?"
./alive
