#!/bin/bash

#kill process with previous brandon-bot
pid=$(ps -x | pgrep -f "[b]randon.py")
if [ -z ${pid} ]; then
    echo "brandon-bot was not running"
else
    echo "sleep, brandon-bot"
    echo "ending process with pid: ${pid}"
    kill ${pid}
fi
